export type RateType = 'fixed' | 'float';

export type TermUnit = 'days' | 'months' | 'years';

/**
 * Capitalization frequency presets.
 * - none: interest is not compounded; it accrues and is settled once at the end of term.
 */
export type CapitalizationFrequency
    = | 'none'
        | 'daily'
        | 'weekly'
        | 'twiceMonthly'
        | 'thriceMonthly'
        | 'monthly'
        | 'quarterly'
        | 'semiAnnual'
        | 'annual';

/** A single segment of a variable (float) interest rate, expressed as ISO date strings (yyyy-MM-dd). */
export interface FloatRateSegment {
    /** Inclusive start date, ISO yyyy-MM-dd. */
    from: string;
    /** Inclusive end date, ISO yyyy-MM-dd. */
    to: string;
    /** Annual interest rate in percent, e.g. 7.5 for 7.5%. */
    rate: number;
}

export interface Term {
    value: number;
    unit: TermUnit;
}

/** How additional contributions to the deposit are modelled. */
export type AdditionType = 'none' | 'recurring' | 'oneTime';

export type RecurringAdditionFrequency = 'monthly' | 'quarterly' | 'annual';

/** A fixed amount added at a regular interval over the term. */
export interface RecurringAddition {
    amount: number;
    frequency: RecurringAdditionFrequency;
}

/** A one-off contribution on a specific date. */
export interface OneTimeAddition {
    /** Contribution date, ISO yyyy-MM-dd. */
    date: string;
    amount: number;
    /**
   * Optional income tax in percent applied only to the income generated by this
   * contribution. When omitted, the deposit's main income tax rate is used.
   */
    taxPercent?: number;
}

/** How withdrawals from the deposit are modelled. */
export type WithdrawalType = 'none' | 'recurring' | 'oneTime';

export type RecurringWithdrawalFrequency = 'monthly' | 'quarterly' | 'annual';

/** A fixed amount withdrawn at a regular interval over the term. */
export interface RecurringWithdrawal {
    amount: number;
    frequency: RecurringWithdrawalFrequency;
}

/** A one-off withdrawal on a specific date. */
export interface OneTimeWithdrawal {
    /** Withdrawal date, ISO yyyy-MM-dd. */
    date: string;
    amount: number;
}

/** Granularity for the period-by-period breakdown. */
export type DetailPeriod = 'changes' | 'daily' | 'monthly' | 'quarterly' | 'annual';

export interface DepositInput {
    /** Initial principal amount. */
    amount: number;
    /** Deposit start date, ISO yyyy-MM-dd. */
    startDate: string;
    term: Term;
    rateType: RateType;
    /** Annual rate in percent used when rateType === 'fixed'. */
    fixedRate: number;
    /** Rate schedule used when rateType === 'float'. */
    floatSchedule: FloatRateSegment[];
    /** Whether interest is capitalized (compounded). */
    capitalization: boolean;
    /** Capitalization frequency; ignored (treated as 'none') when capitalization is false. */
    capFrequency: CapitalizationFrequency;
    /** Income tax in percent applied to interest, e.g. 13 for 13%. */
    incomeTaxPercent: number;
    /** How additional contributions are modelled. */
    additionType: AdditionType;
    /** Recurring contribution settings; used when additionType === 'recurring'. */
    recurringAddition: RecurringAddition;
    /** One-off contributions; used when additionType === 'oneTime'. */
    oneTimeAdditions: OneTimeAddition[];
    /** How withdrawals are modelled. */
    withdrawalType: WithdrawalType;
    /** Recurring withdrawal settings; used when withdrawalType === 'recurring'. */
    recurringWithdrawal: RecurringWithdrawal;
    /** One-off withdrawals; used when withdrawalType === 'oneTime'. */
    oneTimeWithdrawals: OneTimeWithdrawal[];
}

export interface PeriodDetail {
    /** First day of the period, ISO yyyy-MM-dd. */
    periodStart: string;
    /** Last day of the period, ISO yyyy-MM-dd. */
    periodEnd: string;
    openingBalance: number;
    /** Contributions added to the balance during the period. */
    added: number;
    /** Amounts withdrawn from the balance during the period. */
    withdrawn: number;
    /** Gross interest accrued during the period. */
    interestAccrued: number;
    /** Tax paid on interest during the period. */
    taxPaid: number;
    /** Net interest added to the balance during the period (capitalization events). */
    capitalized: number;
    closingBalance: number;
}

export interface DepositResult {
    /** Final balance net of tax. */
    finalBalance: number;
    /** Total net interest income (finalBalance - total contributions). */
    totalIncome: number;
    /** Total tax paid over the term. */
    totalTax: number;
    /** Total gross interest accrued over the term. */
    totalGrossInterest: number;
    /** Total amount contributed (initial principal plus all additions). */
    totalContributions: number;
    /** Total amount withdrawn over the term. */
    totalWithdrawals: number;
    /** Effective annual interest rate as a fraction, e.g. 0.0725 for 7.25%. */
    effectiveAnnualRate: number;
    /** Total return over the whole term as a fraction (compound, net of tax). */
    totalRate: number;
    /** Total rate divided by the term in years (simple annualization). */
    totalAnnualRate: number;
    /** Term length expressed in years. */
    termYears: number;
    /** Total number of days in the term. */
    totalDays: number;
    endDate: string;
    /** Day-by-day breakdown; aggregate to coarser periods with aggregateDetails. */
    dailyDetails: PeriodDetail[];
}

export class DepositValidationError extends Error {
    constructor(
    /** Stable, translatable error code. */
        public readonly code: string,
        /** Optional interpolation values for the message. */
        public readonly params?: Record<string, string | number>
    ) {
        super(code);
        this.name = 'DepositValidationError';
    }
}
